run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - tmp
  modules-download-mode: readonly

linters:
  enable:
    - errcheck        # Check for unchecked errors
    - gosimple        # Simplify code
    - govet           # Vet examines Go source code
    - ineffassign     # Detect ineffectual assignments
    - staticcheck     # Go static analysis
    - unused          # Check for unused code
    - gofmt           # Check formatting
    - goimports       # Check import ordering
    - misspell        # Check for misspelled words
    - revive          # Fast, configurable linter
    - gosec           # Security-focused linter
    - bodyclose       # Check HTTP response body is closed
    - noctx           # Detect sending HTTP request without context
    - unconvert       # Remove unnecessary type conversions
    - unparam         # Find unused function parameters
    - gocritic        # Opinionated Go linter

  disable:
    - typecheck       # Can be noisy with build tags

linters-settings:
  errcheck:
    check-blank: true
    check-type-assertions: false
    exclude-functions:
      - (io.Closer).Close
      - (*database/sql.Rows).Close
      - (*database/sql.DB).Close

  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment

  goimports:
    local-prefixes: veilwarden

  gosec:
    excludes:
      - G404  # Use of weak random number generator (math/rand) - OK for request IDs

  revive:
    rules:
      - name: exported
        disabled: false
        arguments:
          - "checkPrivateReceivers"
          - "disableStutteringCheck"
      - name: package-comments
        disabled: true  # Don't require package comments
      - name: var-naming
        disabled: false
      - name: unexported-return
        disabled: true

  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - commentFormatting
      - whyNoLint

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - gocritic

    # Exclude duplicate error definitions in different files
    - text: "G101: Potential hardcoded credentials"
      linters:
        - gosec

    # Allow fmt.Println in main.go for CLI output
    - path: main\.go
      linters:
        - forbidigo

  exclude-use-default: false

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: false
  sort-results: true
